pipeline { 
agent any
//tools {nodejs "node"}

 stages {
  stage('git'){
   steps{
    git credentialsId: 'github', url: 'https://github.com/monsvt/Academy_Project'
   }
  }
  stage('unit test'){
   steps{
    sh """
    cd node
    echo 'Running test...'
    """
    //sh ' echo "hello world" '
   }
  }
  //stage('Linting'){
   //steps{
    //sh """
    //cd node
    //eslint .
    //"""
   //}
  //}
  stage('SonarQube'){
    environment {
        scannerHome = tool 'SonarQubeScanner'
    }
   steps {
    withSonarQubeEnv('SonarQube') {
            sh "${scannerHome}/bin/sonar-scanner"
        }
        timeout(time: 10, unit: 'MINUTES') {
           waitForQualityGate abortPipeline: true
        }
   }
  }
  stage('Install dependencies & build'){
   environment{
  EXECUTE = true
 }
   steps{
    sh """
    cd node
    npm install
    npm start &
    """
   }
  }
 }
}
