pipeline { 
agent any
tools {nodejs "node"}
//environment{
  //EXECUTE = true
 //}

 stages {
  stage('git'){
   steps{
    git credentialsId: 'github', url: 'https://github.com/monsvt/Academy_Project'
   }
  }
   
   stage('Install dependencies & build'){
   steps{
    sh """
    cd node
    npm install
    """
   }
  }
   
  stage('unit test'){
   steps{
    sh """
    cd node
    echo 'Running test...'
    """
     //npm test
   }
  }
  /*
  stage('Linting'){
   steps{
    sh """
    cd node
    eslint .
    """
   }
  }
  stage('SonarQube'){
    environment {
        scannerHome = tool 'SonarQubeScanner'
    }
   steps {
    withSonarQubeEnv('SonarQube') {
            sh "${scannerHome}/bin/sonar-scanner"
        }
        timeout(time: 10, unit: 'MINUTES') {
           waitForQualityGate abortPipeline: true
        }
   }
  }
  */
   stage('Deployment'){
     steps{
       sh """
       cd node
       npm start &
       """
     }
   }
  
 }
}
