pipeline { 
agent any
 environment{
  EXECUTE = true
 }
 stages {
  stage('git'){
   steps{
    git credentialsId: 'github', url: 'https://github.com/monsvt/Academy_Project'
   }
  }
  //stage('Install dependencies'){
   //steps{
    //sh """
    //cd node
    //npm install
    //"""
   //}
  //}
  stage('unit test'){
   steps{
    
    sh """
    cd node
    pwd
    """
    //sh ' echo "hello world" '
   }
  }
 }
}
